### PR TITLE
Multi-pipeline build

### PR DESCRIPTION
**Pull request by OwenArnold**
Should address a number (but not all) issues listed in https://github.com/scipp/scipp/issues/1570

* parameterised builds - can specify *publish*, *git_revision*, *mantid_version*
* cron job for nightly build (new pipeline)
* Update to existing broken pipeline (liblapack version)

See demo run of schedule
https://dev.azure.com/scipp/mantid-framework-conda-recipe/_build/results?buildId=2981&view=results

See working "prototype" pipelines
https://dev.azure.com/scipp/mantid-framework-conda-recipe/_build

**AFTER MERGING**
- update triggers and branches in release.yaml, cron.yaml (should be master)
- update pipelines on azure to use master branch and rename
- Add status badges for pipelines.

### CODE REVIEW

**Review by nvaytet — APPROVED** [review]
In the future, it would be good to remove the duplication between the Linux and OSX steps.
As far as I can see, the only difference is the `sudo chown -R $USER $CONDA` step.

**Comment by OwenArnold** [comment]
> In the future, it would be good to remove the duplication between the Linux and OSX steps.
> As far as I can see, the only difference is the `sudo chown -R $USER $CONDA` step.

Also vmimage, but agree. Subsequent common steps could be made the same.

**Comment by DanNixon** [comment]
> As far as I can see, the only difference is the `sudo chown -R $USER $CONDA` step.

You can include this on both, I can't quite remember why it is needed on Mac, but for the sake of simplicity it can be on both without issue.

**Comment by OwenArnold** [comment]
> > As far as I can see, the only difference is the `sudo chown -R $USER $CONDA` step.
> 
> You can include this on both, I can't quite remember why it is needed on Mac, but for the sake of simplicity it can be on both without issue.

Thanks Dan. Good point. I'll make another update (PR) to try to make the jobs the same.

**Pull request merged**
